spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/devdb
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        show_sql: true
        hibernate:
            ddl-auto: create
    application:
        name: esercizio-76-aggiungiamo-hibernate-alla-app-sprint-boot
